from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


DATA_FOLDER_NAME = 'data'

PREDICT_FOLDER_NAME = 'predict'

VISUALISATION_FOLDER_NAME = 'visualisation'

TEST_SIZE = 0.3

MODELS = {
    0: {'estimator_name': 'CatBoost',
        'is_linear': False,
        'params': {'learning_rate': [0.1, 0.5, 1], 'iterations': [100, 500, 1000], 'depth': [5, 10, 15, 30],
                   'n_jobs': [-1]},
        'model': CatBoostClassifier},
    1: {'estimator_name': 'LGBM',
        'is_linear': False,
        'params': {'learning_rate': [0.1, 0.5, 1], 'n_estimators': [100, 500, 1000], 'max_depth': [5, 10, 15, 30],
                   'n_jobs': [-1]},
        'model': LGBMClassifier},
    2: {'estimator_name': 'Decision tree',
        'is_linear': False,
        'params': {'max_depth': [5, 10, 15, 30]},
        'model': DecisionTreeClassifier},
    3: {'estimator_name': 'Random Forest',
        'is_linear': False,
        'params': {'n_estimators': [100, 500, 1000], 'max_depth': [5, 10, 15, 30],
                   'n_jobs': [-1]},
        'model': RandomForestClassifier},
    4: {'estimator_name': 'KNN',
        'is_linear': True,
        'params': {'n_neighbors': [5, 10, 15],
                   'n_jobs': [-1]},
        'model': KNeighborsClassifier},
    5: {'estimator_name': 'LogReg',
        'is_linear': True,
        'params': {'C': [1.0, 0.5, 0.2], 'max_iter': [100, 200, 500],
                   'n_jobs': [-1]},
        'model': LogisticRegression},
    6: {'estimator_name': 'SVC',
        'is_linear': True,
        'params': {'C': [1.0, 0.5, 0.2], 'kernel': ['linear', 'poly'], 'probability': ['True']},
        'model': SVC},
    7: {'estimator_name': 'Naive Bayes',
        'is_linear': True,
        'params': {'priors': [None]},
        'model': GaussianNB},





}

DATAFRAMES = {
    'turnover.csv': {'features': ['stag',
                                  'gender',
                                  'age',
                                  'industry',
                                  'profession',
                                  'traffic',
                                  'coach',
                                  'head_gender',
                                  'greywage',
                                  'way',
                                  'extraversion',
                                  'independ',
                                  'selfcontrol',
                                  'anxiety',
                                  'novator'],
                     'y': 'event'},
    'employees.csv': {'features': ['Project_Id',
                                   'Start_Date',
                                   'End_Date',
                                   'Allocated_Days',
                                   'Completed_In_Days',
                                   'Login_Time',
                                   'Logout_Time',
                                   'Joining_Date',
                                   'Appraisal_Cycles'],
                      'y': 'isOnTime'},
    'Train.csv': {'features': ['Gender',
                               'Age',
                               'Education_Level',
                               'Relationship_Status',
                               'Hometown',
                               'Unit',
                               'Decision_skill_possess',
                               'Time_of_service',
                               'Time_since_promotion',
                               'growth_rate',
                               'Travel_Rate',
                               'Post_Level',
                               'Pay_Scale',
                               'Compensation_and_Benefits',
                               'Work_Life_balance',
                               'VAR1',
                               'VAR2',
                               'VAR3',
                               'VAR4',
                               'VAR5',
                               'VAR6',
                               'VAR7', ],
                  'y': 'Attrition_rate'},
    'Attrition_data Fix location.csv': {'features': ['DOJ',
                                                     'Designation',
                                                     'Grade',
                                                     'Attrition ',
                                                     'Location',
                                                     'In Active Date',
                                                     'Gender',
                                                     'Education',
                                                     'Age',
                                                     'Last Rating',
                                                     'Monthly Income',
                                                     'Engagement Score (% Satisfaction)',
                                                     'Marital Status',
                                                     'Zone',
                                                     'Remarks',
                                                     'lower location',
                                                     'DoubtFul',
                                                     'Fixed Location',
                                                     'Changed',
                                                     'location_remarks',
                                                     'City/District',
                                                     'State',
                                                     'zone_lower',
                                                     'state_remarks'],
                                        'y': 'Tenure'},
    'train(1).csv': {'features': ['satisfaction_level',
                                  'last_evaluation_rating',
                                  'projects_worked_on',
                                  'average_montly_hours',
                                  'time_spend_company',
                                  'Work_accident',
                                  'promotion_last_5years',
                                  'Department',
                                  'salary', ],
                     'y': 'Attrition'},
    'HR_comma_sep.csv': {'features': ['satisfaction_level',
                                      'last_evaluation',
                                      'number_project',
                                      'average_montly_hours',
                                      'time_spend_company',
                                      'Work_accident',
                                      'left',
                                      'promotion_last_5years',
                                      'sales',
                                      'salary'],
                         'y': 'left'},
    'MFGEmployees4.csv': {'features': ['Gender',
                                       'City',
                                       'JobTitle',
                                       'DepartmentName',
                                       'StoreLocation',
                                       'Division',
                                       'Age',
                                       'AbsentHours',
                                       'BusinessUnit',
                                       'LengthService'],
                          'y': 'AbsentHours'},
    'Absenteeism_at_work_Project.csv': {'features': ['Reason for absence',
                                                     'Month of absence',
                                                     'Day of the week',
                                                     'Seasons',
                                                     'Transportation expense',
                                                     'Distance from Residence to Work',
                                                     'Service time',
                                                     'Age',
                                                     'Work load Average/day ',
                                                     'Hit target',
                                                     'Disciplinary failure',
                                                     'Education',
                                                     'Son',
                                                     'Social drinker',
                                                     'Social smoker',
                                                     'Pet',
                                                     'Weight',
                                                     'Height',
                                                     'Body mass index'],
                                        'y': 'Absenteeism time in hours'},
    'HRDataset_v14.csv': {'features': ['MarriedID',
                                       'MaritalStatusID',
                                       'GenderID',
                                       'EmpStatusID',
                                       'DeptID',
                                       'PerfScoreID',
                                       'FromDiversityJobFairID',
                                       'Salary',
                                       'Termd',
                                       'PositionID',
                                       'Position',
                                       'State',
                                       'Zip',
                                       'DOB',
                                       'Sex',
                                       'MaritalDesc',
                                       'CitizenDesc',
                                       'HispanicLatino',
                                       'RaceDesc',
                                       'DateofHire',
                                       'DateofTermination',
                                       'TermReason',
                                       'EmploymentStatus',
                                       'Department',
                                       'ManagerName',
                                       'ManagerID',
                                       'RecruitmentSource',
                                       'PerformanceScore',
                                       'EngagementSurvey',
                                       'EmpSatisfaction',
                                       'SpecialProjectsCount',
                                       'LastPerformanceReview_Date',
                                       'DaysLateLast30'],
                          'y': 'Absences'},
    'WA_Fn-UseC_-HR-Employee-Attrition.csv': {'features': ['Age',
                                                           'BusinessTravel',
                                                           'DailyRate',
                                                           'Department',
                                                           'DistanceFromHome',
                                                           'Education',
                                                           'EducationField',
                                                           'EmployeeCount',
                                                           'EmployeeNumber',
                                                           'EnvironmentSatisfaction',
                                                           'Gender',
                                                           'HourlyRate',
                                                           'JobInvolvement',
                                                           'JobLevel',
                                                           'JobRole',
                                                           'JobSatisfaction',
                                                           'MaritalStatus',
                                                           'MonthlyIncome',
                                                           'MonthlyRate',
                                                           'NumCompaniesWorked',
                                                           'Over18',
                                                           'OverTime',
                                                           'PercentSalaryHike',
                                                           'PerformanceRating',
                                                           'RelationshipSatisfaction',
                                                           'StandardHours',
                                                           'StockOptionLevel',
                                                           'TotalWorkingYears',
                                                           'TrainingTimesLastYear',
                                                           'WorkLifeBalance',
                                                           'YearsAtCompany',
                                                           'YearsInCurrentRole',
                                                           'YearsSinceLastPromotion',
                                                           'YearsWithCurrManager'],
                                              'y': 'Attrition'},
    'Employee Data.csv': {'features': ['Gender',
                                       'Satisfaction',
                                       'Business Travel',
                                       'Department',
                                       'EducationField',
                                       'Salary',
                                       'Home-Office'],
                          'y': 'Attrition'},
    'MFG10YearTerminationData.csv': {'features': ['EmployeeID',
                                                  'recorddate_key',
                                                  'birthdate_key',
                                                  'orighiredate_key',
                                                  'terminationdate_key',
                                                  'age',
                                                  'length_of_service',
                                                  'city_name',
                                                  'department_name',
                                                  'job_title',
                                                  'store_name',
                                                  'gender_short',
                                                  'gender_full',
                                                  'termreason_desc',
                                                  'termtype_desc',
                                                  'STATUS_YEAR',
                                                  'BUSINESS_UNIT'],
                                     'y': 'STATUS'},
    'employee_attrition_train.csv': {'features': ['Age',
                                                  'BusinessTravel',
                                                  'DailyRate',
                                                  'Department',
                                                  'DistanceFromHome',
                                                  'Education',
                                                  'EducationField',
                                                  'EmployeeCount',
                                                  'EmployeeNumber',
                                                  'EnvironmentSatisfaction',
                                                  'Gender',
                                                  'HourlyRate',
                                                  'JobInvolvement',
                                                  'JobLevel',
                                                  'JobRole',
                                                  'JobSatisfaction',
                                                  'MaritalStatus',
                                                  'MonthlyIncome',
                                                  'MonthlyRate',
                                                  'NumCompaniesWorked',
                                                  'Over18',
                                                  'OverTime',
                                                  'PercentSalaryHike',
                                                  'PerformanceRating',
                                                  'RelationshipSatisfaction',
                                                  'StandardHours',
                                                  'StockOptionLevel',
                                                  'TotalWorkingYears',
                                                  'TrainingTimesLastYear',
                                                  'WorkLifeBalance',
                                                  'YearsAtCompany',
                                                  'YearsInCurrentRole',
                                                  'YearsSinceLastPromotion',
                                                  'YearsWithCurrManager'],
                                     'y': 'Attrition'},
}
